# Generated by Django 5.1.1 on 2024-09-04 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('todo', 'A Fazer'), ('in_progress', 'Em Progresso'), ('review', 'Em Revisão'), ('done', 'Concluído')], default='todo', max_length=20),
        ),
    ]
