# Generated by Django 5.1.1 on 2024-09-12 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('todo', 'to-do'), ('in-progress', 'in-progress'), ('review', 'review'), ('done', 'done')], default='todo', max_length=20),
        ),
    ]
